// Dựng `BaiGhepSoDo` cho test canvas. Đủ trường để component render thật, và chỉ những trường
// test quan tâm mới phải khai — phần còn lại là mặc định vô hại.
import type { BaiGhepSoDo, BaiGhepSoDoBuocChung, BaiGhepSoDoNhanh, BaiGhepSoDoNode } from "../api/client";

export function buoc(over: Partial<BaiGhepSoDoNode> & { step_key: string }): BaiGhepSoDoNode {
  return {
    ten: "In offset",
    nhom: "print",
    loai_buoc: "may",
    thu_tu: 0,
    cong_doan_id: 1,
    gop_step_key: null,
    to_ten: "Tổ in",
    may_ten: "Máy 5 màu",
    nha_cung_cap: null,
    tong_phut: 60,
    chiem_may_phut: 60,
    phu_thuoc_step_keys: [],
    so_luong_vao: 5000,
    so_luong_ra: 5000,
    don_vi_vao: "to",
    don_vi_ra: "to",
    hao_hut: 0,
    ...over,
  };
}

export function nhanh(
  over: Partial<BaiGhepSoDoNhanh> & { lsx_id: number; buoc: BaiGhepSoDoNode[] },
): BaiGhepSoDoNhanh {
  return {
    thanh_vien_id: over.lsx_id,
    lsx_ma: `LSX-${over.lsx_id}`,
    lsx_ten: null,
    customer_name: "Khách A",
    han_hoan_thanh_sx: null,
    is_rush: false,
    mau: 0,
    so_con_tren_to: 2,
    toa_step_key: null,
    nhu_cau_to: 4000,
    du_to: 0,
    phan_giay_to: 0,
    ty_le_giay: 0,
    san_luong_du_kien: 8000,
    du: 0,
    ...over,
  };
}

export function gop(
  over: Partial<BaiGhepSoDoBuocChung> & { step_key: string; thanh_vien: BaiGhepSoDoBuocChung["thanh_vien"] },
): BaiGhepSoDoBuocChung {
  return {
    ten: "In offset",
    nhom: "print",
    cong_doan_id: 1,
    loai_buoc: "may",
    thu_tu: 0,
    so_luong_vao: 5075,
    so_luong_ra: 5075,
    don_vi_vao: "to",
    don_vi_ra: "to",
    he_so_quy_doi: 1,
    so_luong_ra_quy: 5075,
    hao_hut: 0,
    hao_hut_pct: 0,
    canh_bao_don_vi: [],
    da_lap_ke_hoach: false,
    department_id: null,
    to_ten: null,
    may_id: null,
    may_ten: null,
    nha_cung_cap: null,
    tong_phut: 90,
    chiem_may_phut: 90,
    so_nhan_cong: 1,
    nang_suat: null,
    don_vi_nang_suat: null,
    chay_phut: null,
    setup_phut: 0,
    ve_sinh_phut: 0,
    cho_phut: 0,
    di_chuyen_phut: 0,
    so_luot_chay: 1,
    khoan_rate_id: null,
    khoan_ten: null,
    khoan_don_vi: null,
    khoan_don_gia: null,
    khoan_chon_duoc: [],
    khoan_sl: null,
    khoan_don_vi_sl: null,
    khoan_tien: null,
    khoan_dien_giai: null,
    khoan_thieu: [],
    khoan_ly_do: null,
    vat_tus: [],
    sl_gui: null,
    ngay_gui_dk: null,
    van_chuyen_ngay: null,
    gia_cong_ngay: null,
    ngay_nhan_dk: null,
    hao_hut_cho_phep: null,
    don_gia_gia_cong: null,
    yeu_cau_ky_thuat: null,
    ghi_chu: null,
    ma_bai_ghep: "GB26-0001",
    thieu: [],
    ...over,
  };
}

export function soDo(over: Partial<BaiGhepSoDo> = {}): BaiGhepSoDo {
  return {
    bai_ghep: {
      id: 1,
      ma: "GB26-0001",
      trang_thai: "nhap",
      may_id: null,
      may_ten: null,
      giay_id: null,
      giay_ten: "Ivory 350",
      kho_in_dai: 650,
      kho_in_rong: 900,
      hao_hut_setup: null,
      hao_hut_chay: null,
      so_to_tot: 5075,
      tong_to: 5325,
      fill_pct: 82,
      hao_de_xuat: 250,
      hao_setup_de_xuat: 250,
      hao_chay_de_xuat: 0,
      to_nguyen_can: 5325,
      so_buoc_chung: 0,
    },
    nhanh: [],
    gop: [],
    ngoai: [],
    ...over,
  };
}
